### ISSUE TITLE
pretrained weights for dilated_fcn8s

### ISSUE THREAD

**Issue by IssamLaradji** [MSiam/AdaptiveMaskedProxies#7]
Hi there,

Where can I find the pretrained weights for `dilated_fcn8s`, the model used for `configs/fcn8s_pascal_imprinted.yml` in `fewshot_imprinted.py`?

**Comment by MSiam** [comment]
All models including both the reduced version and dilated one is in runs.zip [here](https://drive.google.com/drive/folders/1wJXetJCGkT_xej8Jr8Mrj9vJUHN8EtJu):

You can find the instructions to reproduce experiments [here](https://github.com/MSiam/AdaptiveMaskedProxies/blob/master/Experiments.md)

**Comment by IssamLaradji** [comment]
Thanks!
