### ISSUE TITLE
model.reverse_imprinting

### ISSUE THREAD

**Issue by Xiangyi1996** [MSiam/AdaptiveMaskedProxies#9]
In fewshot_imprinted.py 

`# Reverse the last imprinting (Few shot setting only not Continual Learning setup yet)
        model.reverse_imprinting()`

To reuse the original weight for each iteration, means we don't use the previous imprinted weight.  
Maybe we could use the previous weight[:16] except for the final novel weight instead of just abandon all 17 imprinted weight and use the original(VGG) weight?

**Comment by MSiam** [comment]
Yes its already doing what you want. This is not reusing the original VGG16 weights, but rather using the weights from the loaded model.

Note line 116 [here](https://github.com/MSiam/AdaptiveMaskedProxies/blob/master/fewshot_imprinted.py) it is saving weights after the model is loaded. These are the ones used in reverse_imprinting

**Comment by Xiangyi1996** [comment]
Oh, sorry, I means use the imprinted weight[:16] from previous iterations, instead of using a never changed loaded model weight for the base classes, especially in imprinted-finetune processing, since we change all the weight in each "task-test".
Is the target to remember what we get from the trained 15 base segmentator, and just learn new class one by one iterations and never change the base weight?

**Comment by MSiam** [comment]
Cause this is more like the continual learning mode, you can check ipascal exps. While in the few-shot mode you're expected to only learn from one support set with k examples. If I kept the previous ones it implicitly means that I am learning from multiple support sets. So for fair comparison I am not.
